version: "3.8"


services:
    remark:
        build: .
        image: umputun/remark42:latest
        container_name: "remark42"
        hostname: "remark42"
        restart: always

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        # uncomment to expose directly (no proxy)
        ports:
         - "8081:8080"

        env_file:
            - envs/remark42.env
            - envs/remark42_overrides.env


        environment:
            - AUTH_GOOGLE_CID
            - AUTH_GOOGLE_CSEC
            - AUTH_GITHUB_CID
            - AUTH_GITHUB_CSEC
            - AUTH_FACEBOOK_CID
            - AUTH_FACEBOOK_CSEC
            - AUTH_DISQUS_CID
            - AUTH_DISQUS_CSEC
            # - ADMIN_PASSWD=password
        volumes:
            - ./var:/srv/var