version: "3.8"


services:
    remark:
        image: umputun/remark42:latest
        container_name: "remark42"
        hostname: "remark42"
        restart: always

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        # uncomment to expose directly (no proxy)
        ports:
         - "8081:8080"

        env_file:
            - ./envs/remark42.env
            - ./envs/remark42_overrides.env

        labels:
                - 'traefik.enable=true'
                - 'traefik.http.routers.comments.rule=Host(`comments.jeppe.science`)'
                - 'traefik.http.routers.comments.entrypoints=websecure'
                - 'traefik.http.routers.comments.tls.certresolver=letsencrypt'

        networks:
            - web

        volumes:
            - ./var:/srv/var

networks:
    web:
        external: true