[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.82.0"
  HUGO_ENABLEGITINFO = "true"
#  GIT_LFS_ENABLED = "true"
#! NOTE GIT_LFS_ENABLED MUST BE SET ON THE UI.
# See: https://docs.netlify.com/configure-builds/environment-variables/#netlify-configuration-variables

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

# HTTP header stuff
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
