[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.105.0"
  HUGO_ENABLEGITINFO = "true"
#  GIT_LFS_ENABLED = "true"
#! NOTE GIT_LFS_ENABLED MUST BE SET ON THE UI.
# See: https://docs.netlify.com/configure-builds/environment-variables/#netlify-configuration-variables

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# HTTP header stuff
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Access-Control-Allow-Origin = "https://comments.jeppe.science"

# Redirects
# [[redirects]]
#   from = "http://jeppe.science/"
#   to = "https://jeppe.science/"
#   status = 301
#   force = true #COMMENT: ensure that we always redirect

# Plugins
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
    debug = true

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://jeppe.science/"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]
