---
version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    container_name: umami
    hostname: umami
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: 6TVgv9meZrFkbUfLpztxqSCocnPy64sG
    depends_on:
      - db
    restart: always
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"

      traefik.http.routers.umami.rule: "Host(`analytics.jeppe.science`)"
      traefik.http.routers.umami.entrypoints: "websecure"
      traefik.http.routers.umami.tls.certresolver: "letsencrypt"
      traefik.http.services.umami.loadbalancer.server.port: 3000
      traefik.http.routers.umami.service: umami

  db:
    image: postgres:12-alpine
    container_name: umami_db
    hostname: umami_db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - default

volumes:
  umami-db-data:

networks:
  web:
    external: true
